"""lang in post

Revision ID: 077db0137f62
Revises: 1b0bf7346fc2
Create Date: 2018-01-08 11:28:38.291256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077db0137f62'
down_revision = '1b0bf7346fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
