"""user info fields

Revision ID: 98297c2b8665
Revises: 3edfc17dc67d
Create Date: 2017-12-30 13:00:37.031202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98297c2b8665'
down_revision = '3edfc17dc67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
